Implementación
IslasGECI/change_state_traps pull request #1
Opened 2020-07-30 15:50 UTC by nepito

2020-08-04 18:03 UTC, evaristor commented
Agregué [esto](https://codecov.io/gh/IslasGECI/change_state_traps/).

2020-08-10 17:03 UTC, devarops requested changes
Aquí dejo mi primer revisión.

Me llamó la atención el uso de `unittest` en lugar de solamente usar Pytest. ¿Hay alguna razón en particular por la que requerimos `unittest`?

2020-08-10 17:03 UTC, devarops commented on Dockerfile
> +CMD make
Por favor podrías agregar fin de línea a la última línea?
```suggestion
CMD make

```

2020-08-10 17:03 UTC, devarops commented on Dockerfile
> +    pytest==5.0.1
Teníamos "amarrada" la versión 5.0.1 de Pytest porque había un _bug_ en una versión posterior 5.X.0, X>0. Recientemente, (julio 31) lanzaron la versión 6.0.1. Tal vez deberíamos probar esa nueva versión?

```suggestion
    pytest
```

2020-08-10 17:03 UTC, devarops commented on Dockerfile
> +FROM python:3.7
La versión actual es 3.8. Tal vez deberíamos dejar libre el 3 y solo anclarlo cuando tengamos un problema?

```suggestion
FROM python:3
```

Hoy, la version 3 apunta a 3.8.5

2020-08-10 17:03 UTC, devarops commented on Makefile
> +	rm --force coverage.xml
```suggestion
	rm --force coverage.xml

```
Por favor podrías agregar fin de línea a la última línea?

2020-08-10 17:03 UTC, devarops commented on setup.py
> +)
¿Por favo podrías agregar fin de línea a la última línea?
```suggestion
)

```

2020-08-10 17:03 UTC, devarops commented on setup.py
> +    python_requires='>=3.7'
Crees que sea posible actualizar la versión de Python?
```suggestion
    python_requires='>=3.8'
```

2020-08-10 17:03 UTC, devarops commented on tests/test_Calculator_Effort_Captures.py
> +    unittest.main()
DUDA: ¿Por qué estamos usando `unittests`? No tengo nada encontra, sólo me llama la atención. Pensé que ya estábamos usnado Pytest sin UnitTest

2020-11-13 02:35 UTC, nepito commented on setup.py
> +    python_requires='>=3.7'
La última vez tuvimos problemas con la versión más nueva

2020-11-13 02:46 UTC, nepito commented on tests/test_Calculator_Effort_Captures.py
> +    unittest.main()
Seguramente aquí todavía no nos habíamos puesto de acuerdo. Acabo de cambiar a pytest uno de los archivos de pruebas.

2021-07-02 20:50 UTC, evaristor commented
PR obsoleto

2021-07-02 20:50 UTC, closed without merging